ATTRIBUTES = {
    'MU': 'Mut',
    'KL': 'Klugheit',
    'IN': 'Intuition',
    'CH': 'Charisma',
    'FF': 'Fingerfertigkeit',
    'GE': 'Gewandheit',
    'KO': 'Konstitution',
    'KK': 'Körperkraft'
}

TALENTS = [
    {'name' : 'Fliegen', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'B', 'probe' : ['MU', 'IN', 'GE']},
    {'name' : 'Gaukeleien', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'A', 'probe' : ['MU', 'CH', 'FF']},
    {'name' : 'Klettern', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'B', 'probe' : ['MU', 'GE', 'KK']},
    {'name' : 'Körperbeherrschung', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'D', 'probe' : ['GE', 'GE', 'KO']},
    {'name' : 'Kraftakt', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'B', 'probe' : ['KO', 'KK', 'KK']},
    {'name' : 'Reiten', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'B', 'probe' : ['CH', 'GE', 'KK']},
    {'name' : 'Schwimmen', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'B', 'probe' : ['GE', 'KO', 'KK']},
    {'name' : 'Selbstbeherrschung', 'kat' : 'Körper', 'be' : 'NEIN', 'stg' : 'D', 'probe' : ['MU', 'MU', 'KO']},
    {'name' : 'Singen', 'kat' : 'Körper', 'be' : 'EVTL', 'stg' : 'A', 'probe' : ['KL', 'CH', 'KO']},
    {'name' : 'Sinnesschärfe', 'kat' : 'Körper', 'be' : 'EVTL', 'stg' : 'D', 'probe' : ['KL', 'IN', 'IN']},
    {'name' : 'Tanzen', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'A', 'probe' : ['KL', 'CH', 'GE']},
    {'name' : 'Taschendiebstahl', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'B', 'probe' : ['MU', 'FF', 'GE']},
    {'name' : 'Verbergen', 'kat' : 'Körper', 'be' : 'JA', 'stg' : 'C', 'probe' : ['MU', 'IN', 'GE']},
    {'name' : 'Zechen', 'kat' : 'Körper', 'be' : 'NEIN', 'stg' : 'A', 'probe' : ['KL', 'KO', 'KK']},
    {'name' : 'Bekehren & Überzeugen', 'kat' : 'Gesellschaft', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['MU', 'KL', 'CH']},
    {'name' : 'Betören', 'kat' : 'Gesellschaft', 'be' : 'EVTL', 'stg' : 'B', 'probe' : ['MU', 'CH', 'CH']},
    {'name' : 'Einschüchtern', 'kat' : 'Gesellschaft', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['MU', 'IN', 'CH']},
    {'name' : 'Etikette', 'kat' : 'Gesellschaft', 'be' : 'EVTL', 'stg' : 'B', 'probe' : ['KL', 'IN', 'CH']},
    {'name' : 'Gassenwissen', 'kat' : 'Gesellschaft', 'be' : 'EVTL', 'stg' : 'C', 'probe' : ['KL', 'IN', 'CH']},
    {'name' : 'Menschenkenntnis', 'kat' : 'Gesellschaft', 'be' : 'NEIN', 'stg' : 'C', 'probe' : ['KL', 'IN', 'CH']},
    {'name' : 'Überreden', 'kat' : 'Gesellschaft', 'be' : 'NEIN', 'stg' : 'C', 'probe' : ['MU', 'IN', 'CH']},
    {'name' : 'Verkleiden', 'kat' : 'Gesellschaft', 'be' : 'EVTL', 'stg' : 'B', 'probe' : ['IN', 'CH', 'GE']},
    {'name' : 'Willenskraft', 'kat' : 'Gesellschaft', 'be' : 'NEIN', 'stg' : 'D', 'probe' : ['MU', 'IN', 'CH']},
    {'name' : 'Fährtensuchen', 'kat' : 'Natur', 'be' : 'JA', 'stg' : 'C', 'probe' : ['MU', 'IN', 'GE']},
    {'name' : 'Fesseln', 'kat' : 'Natur', 'be' : 'EVTL', 'stg' : 'A', 'probe' : ['KL', 'FF', 'KK']},
    {'name' : 'Fischen & Angeln', 'kat' : 'Natur', 'be' : 'EVTL', 'stg' : 'A', 'probe' : ['FF', 'GE', 'KO']},
    {'name' : 'Orientierung', 'kat' : 'Natur', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'IN', 'IN']},
    {'name' : 'Planzenkunde', 'kat' : 'Natur', 'be' : 'EVTL', 'stg' : 'C', 'probe' : ['KL', 'FF', 'KO']},
    {'name' : 'Tierkunde', 'kat' : 'Natur', 'be' : 'JA', 'stg' : 'C', 'probe' : ['MU', 'MU', 'CH']},
    {'name' : 'Wildnisleben', 'kat' : 'Natur', 'be' : 'JA', 'stg' : 'C', 'probe' : ['MU', 'GE', 'KO']},
    {'name' : 'Brett- & Glücksspiel', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'A', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Geographie', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Geschichtswissen', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Götter & Kulte', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Kriegskunst', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['MU', 'KL', 'IN']},
    {'name' : 'Magiekunde', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'C', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Mechanik', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'KL', 'FF']},
    {'name' : 'Rechnen', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'A', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Rechtskunde', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'A', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Sagen & Legenden', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Sphärenkunde', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Sternkunde', 'kat' : 'Wissen', 'be' : 'NEIN', 'stg' : 'A', 'probe' : ['KL', 'KL', 'IN']},
    {'name' : 'Alchimie', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'C', 'probe' : ['MU', 'KL', 'FF']},
    {'name' : 'Boote & Schiffe', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'B', 'probe' : ['FF', 'GE', 'KK']},
    {'name' : 'Fahrzeuge', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'A', 'probe' : ['CH', 'FF', 'KO']},
    {'name' : 'Handel', 'kat' : 'Handwerk', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['KL', 'IN', 'CH']},
    {'name' : 'Heilkunde Gift', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'B', 'probe' : ['MU', 'KL', 'IN']},
    {'name' : 'Heilkunde Krankheiten', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'B', 'probe' : ['MU', 'IN', 'KO']},
    {'name' : 'Heilkunde Seele', 'kat' : 'Handwerk', 'be' : 'NEIN', 'stg' : 'B', 'probe' : ['IN', 'CH', 'KO']},
    {'name' : 'Heilkunde Wunden', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'D', 'probe' : ['KL', 'FF', 'FF']},
    {'name' : 'Holzbearbeitung', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'B', 'probe' : ['FF', 'GE', 'KK']},
    {'name' : 'Lebensmittelbearbeitung', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'A', 'probe' : ['IN', 'FF', 'FF']},
    {'name' : 'Lederbearbeitung', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'B', 'probe' : ['FF', 'GE', 'KO']},
    {'name' : 'Malen & Zeichnen', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'A', 'probe' : ['IN', 'FF', 'FF']},
    {'name' : 'Metallbearbeitung', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'C', 'probe' : ['FF', 'KO', 'KK']},
    {'name' : 'Musizieren', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'A', 'probe' : ['CH', 'FF', 'KO']},
    {'name' : 'Schlösserknacken', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'C', 'probe' : ['IN', 'FF', 'FF']},
    {'name' : 'Steinbearbeitung', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'A', 'probe' : ['FF', 'FF', 'KK']},
    {'name' : 'Stoffbearbeitung', 'kat' : 'Handwerk', 'be' : 'JA', 'stg' : 'A', 'probe' : ['KL', 'FF', 'FF']}
]
